#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# 健康检查
# exec s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1316" \
#    s6-setuidgid abc /app/webserver/bin/server

exec /app/webserver/bin/server