#!/bin/sh
#exec s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3306" \
#    s6-setuidgid mysql /usr/bin/mysqld --user=mysql --basedir=/usr --datadir=/opt/mysql --socket=/run/mysqld/mysqld.sock

# chown -R mysql:mysql /var/lib/mysql

exec /usr/bin/mysqld --user=mysql --datadir=/var/lib/mysql --socket=/run/mysqld/mysqld.sock --bind-address=0.0.0.0 --port=3306 --skip-name-resolve --init-file=/run/mysqld/init.sql